DROP PROCEDURE IF EXISTS dbo.SUM_PRODUCT_SALESYTD;

GO
CREATE PROCEDURE SUM_PRODUCT_SALESYTD AS
BEGIN TRY
    SELECT SUM(SALES_YTD)
    FROM PRODUCT
END TRY

BEGIN CATCH
    DECLARE @ErrorMessage AS NVARCHAR(MAX);
    SET @ErrorMessage = ERROR_MESSAGE();

    THROW 500000, @ErrorMessage, 1

END CATCH

GO
EXEC SUM_PRODUCT_SALESYTD

SELECT * FROM PRODUCT;