DROP PROCEDURE IF EXISTS dbo.SUM_CUSTOMER_SALESYTD;

GO
CREATE PROCEDURE SUM_CUSTOMER_SALESYTD AS
BEGIN TRY
    SELECT SUM(SALES_YTD)
    FROM CUSTOMER
END TRY

BEGIN CATCH
    DECLARE @ErrorMessage AS NVARCHAR(MAX);
    SET @ErrorMessage = ERROR_MESSAGE();

    THROW 500000, @ErrorMessage, 1

END CATCH

GO
EXEC SUM_CUSTOMER_SALESYTD

SELECT * FROM CUSTOMER;